"""
The equilibrium (consistent planning) mean-variance policy.

This supplies the second of the three policies in the proposal's decomposition,
and with it the first error term

    eps_incons = J(pi_pre) - J(pi_eq),

the price of time-consistency.

Definition
----------
Following Strotz (1955) and the Markovian discrete-time theory of Björk and
Murgoci (2014), a policy ``pi_eq`` is an equilibrium if no single-period
deviation improves the objective, given that all later selves continue with
``pi_eq``: for every ``t``, ``x`` and admissible ``a``,

    J(t, x, pi_eq)  >=  J(t, x, (a, pi_eq_{t+1:T})).

This is equation (10) of the proposal.  Unlike the pre-committed problem it is
solved by a genuine backward recursion, because the equilibrium condition is a
one-step condition by construction.

Derivation
----------
Write the two moment functions generated by the equilibrium continuation,

    f(t, x) = E_{t,x}[ x_T ],        g(t, x) = E_{t,x}[ x_T^2 ],

so that J(t, x) = f - phi (g - f^2).  For this market the ansatz

    f(t, x) = A_t x + a_t,           g(t, x) = B_t x^2 + b_t x + c_t

is self-consistent.  At time ``t`` the agent maximises, over ``u``,

    Phi(u) = E[f(t+1, y)] - phi ( E[g(t+1, y)] - E[f(t+1, y)]^2 ),
    y = s x + P^T u.

The first-order condition is linear in ``u`` and gives

    u_t(x) = alpha_t x + beta_t,
    D_{t+1} = B_{t+1} M - A_{t+1}^2 m m^T,      d = D_{t+1}^{-1} m,
    alpha_t = s (A_{t+1}^2 - B_{t+1}) d,
    beta_t  = [ A_{t+1} - phi b_{t+1} + 2 phi A_{t+1} a_{t+1} ] d / (2 phi).

The Hessian of Phi is -2 phi D_{t+1}, so D_{t+1} must be positive definite for
the stationary point to be a maximum; this is checked at every step rather than
assumed.  Substituting the control back into f and g closes the recursion,
started from A_T = 1, a_T = 0, B_T = 1, b_T = c_T = 0.

Note the contrast with the pre-committed case.  There the control depends on a
global multiplier ``lambda`` pinned by E[x_T], which is what makes that policy
depend on the initial condition and hence time-inconsistent.  Here no such
multiplier appears: the recursion is local, and the resulting policy is
independent of ``x_0``.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from .market import Market
from .policies import AffinePolicy


@dataclass
class EquilibriumSolution:
    """The equilibrium policy together with the moment coefficients."""

    policy: AffinePolicy
    A: np.ndarray  # (T+1,)  f(t, x) = A_t x + a_t
    a: np.ndarray  # (T+1,)
    B: np.ndarray  # (T+1,)  g(t, x) = B_t x^2 + b_t x + c_t
    b: np.ndarray  # (T+1,)
    c: np.ndarray  # (T+1,)

    def value(self, t: int, x: float) -> float:
        """J(t, x) under the equilibrium continuation."""
        f = self.A[t] * x + self.a[t]
        g = self.B[t] * x * x + self.b[t] * x + self.c[t]
        return f - self._phi * (g - f * f)


def solve_equilibrium(market: Market, phi: float) -> EquilibriumSolution:
    """Backward recursion for the equilibrium mean-variance policy.

    The policy does not depend on initial wealth, which is one of the ways the
    equilibrium notion differs from the pre-committed one.
    """
    if phi <= 0:
        raise ValueError("phi must be positive")

    T, n = market.horizon, market.n_assets
    A = np.zeros(T + 1)
    a = np.zeros(T + 1)
    B = np.zeros(T + 1)
    b = np.zeros(T + 1)
    c = np.zeros(T + 1)
    A[T], B[T] = 1.0, 1.0  # f(T, x) = x, g(T, x) = x^2

    alpha = np.zeros((T, n))
    beta = np.zeros((T, n))

    for t in range(T - 1, -1, -1):
        s = market.s(t)
        m = market.m(t)
        M = market.M(t)

        D = B[t + 1] * M - (A[t + 1] ** 2) * np.outer(m, m)
        eigenvalues = np.linalg.eigvalsh((D + D.T) / 2.0)
        if eigenvalues.min() <= 0:
            raise ValueError(
                f"at t={t} the one-step problem is not concave "
                f"(min eigenvalue {eigenvalues.min():.3e}); no interior "
                "equilibrium control exists for this market and phi"
            )
        d = np.linalg.solve(D, m)

        alpha[t] = s * (A[t + 1] ** 2 - B[t + 1]) * d
        beta[t] = (
            (A[t + 1] - phi * b[t + 1] + 2.0 * phi * A[t + 1] * a[t + 1])
            * d
            / (2.0 * phi)
        )

        # close the recursion by propagating the two moment functions
        m_alpha = float(m @ alpha[t])
        m_beta = float(m @ beta[t])
        aMa = float(alpha[t] @ M @ alpha[t])
        aMb = float(alpha[t] @ M @ beta[t])
        bMb = float(beta[t] @ M @ beta[t])

        A[t] = A[t + 1] * (s + m_alpha)
        a[t] = A[t + 1] * m_beta + a[t + 1]

        B[t] = B[t + 1] * (s * s + 2.0 * s * m_alpha + aMa)
        b[t] = B[t + 1] * (2.0 * s * m_beta + 2.0 * aMb) + b[t + 1] * (s + m_alpha)
        c[t] = B[t + 1] * bMb + b[t + 1] * m_beta + c[t + 1]

    solution = EquilibriumSolution(
        policy=AffinePolicy(alpha=alpha, beta=beta), A=A, a=a, B=B, b=b, c=c
    )
    solution._phi = phi  # type: ignore[attr-defined]
    return solution


def deviation_value(
    market: Market,
    solution: EquilibriumSolution,
    phi: float,
    t: int,
    x: float,
    u: np.ndarray,
) -> float:
    """J(t, x, (u, pi_eq_{t+1:T})): deviate once at t, then follow equilibrium.

    This is the quantity the equilibrium condition maximises, and evaluating it
    directly is how the solution is verified.
    """
    s, m, M = market.s(t), market.m(t), market.M(t)
    u = np.asarray(u, dtype=float)

    mean_y = s * x + float(m @ u)
    second_y = s * s * x * x + 2.0 * s * x * float(m @ u) + float(u @ M @ u)

    f = solution.A[t + 1] * mean_y + solution.a[t + 1]
    g = solution.B[t + 1] * second_y + solution.b[t + 1] * mean_y + solution.c[t + 1]
    return f - phi * (g - f * f)


def equilibrium_policy(market: Market, phi: float) -> AffinePolicy:
    """Convenience wrapper returning only the policy."""
    return solve_equilibrium(market, phi).policy
