from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[1]
rows=[]
def add(key,authors,title,year,venue,url,version,locator,problem,objective,reward,algorithm,market,metric,result,studies,time,benchmark,relation):
 rows.append(dict(key=key,authors=authors,title=title,year=year,venue=venue,url=url,version=version,locator=locator,problem=problem,objective=objective,reward=reward,algorithm=algorithm,market=market,metric=metric,result=result,studies_reward_objective=studies,time_inconsistency=time,known_benchmark=benchmark,project_relation=relation))
add('kolm2019','Petter N. Kolm; Gordon Ritter','Dynamic Replication and Hedging: A Reinforcement Learning Approach',2019,'The Journal of Financial Data Science 1(1), 159–171','https://doi.org/10.3905/jfds.2019.1.1.159','16-page author manuscript at smallake.kr; figures are missing in this manuscript. Text and equations read; journal PDF unavailable.','“Automatic hedging in theory”, manuscript pp. 7–8, Eqs. (8)–(10), footnote 4; “Automatic hedging in practice”, pp. 9–14, Exhibits 1–5.','Discrete option hedging with nonlinear trading costs.','Terminal wealth mean–variance, then a simplified sum of increment variances.','Δw − (κ/2)(Δw)², explicitly approximate.','Batch fitted action-value learning with one-step SARSA targets and nonlinear regression.','Simulated GBM European call; strike/spot 100, 10 days, 5 decisions/day; κ=.1.','Hedging P&L, costs, volatility; comparison to delta hedging.','Reports lower cost across 10,000 test paths; volatility difference not significant at 99%.','Yes: explicitly discusses covariance and approximation.','Does not formulate a subgame equilibrium in the inspected derivation.','BSM hedge in frictionless limit; not a solved frictional optimum.','Closest raw-reward baseline. We isolate policy mismatch in a different allocation benchmark; do not infer failure of their hedger. Published κ/2=.05 is a units-sensitive diagnostic only.')
add('jiang2017','Zhengyao Jiang; Dixing Xu; Jinjun Liang','A Deep Reinforcement Learning Framework for the Financial Portfolio Management Problem',2017,'arXiv preprint 1706.10059','https://arxiv.org/abs/1706.10059','arXiv v2, 16 July 2017; saved PDF.','§§2.2–2.4, §4.2 Eqs. (21)–(22), §4.3; Tables 1–2; §6.','Long-only cryptocurrency allocation with costs.','Portfolio growth.','Average log portfolio growth including transaction-cost factor.','Direct gradient ascent; EIIE CNN/RNN/LSTM policies and portfolio-vector memory.','Poloniex, 11 noncash assets plus Bitcoin cash, 30-minute decisions; three 2016–2017 backtests.','Final accumulated value, Sharpe, maximum drawdown.','EIIE variants report leading accumulated values in all three tests (Table 2).','Yes: log reward corresponds to multiplicative growth.','No terminal mean–variance equilibrium objective.','Trading comparators, no known true market optimum.','Adapt log growth on an identical bounded action set. Different target preferences explain disagreement; their own growth objective is not mis-specified.')
add('yang2020','Hongyang Yang; Xiao-Yang Liu; Shan Zhong; Anwar Walid','Deep Reinforcement Learning for Automated Stock Trading: An Ensemble Strategy',2020,'Proceedings of the First ACM International Conference on AI in Finance (ICAIF), 8 pages','https://doi.org/10.1145/3383455.3422540','Columbia-hosted author manuscript; saved PDF. Do not use the later 2025 arXiv upload as a 2020 identifier.','§3.3 Eq. (4); §5 ensemble selection; §6.1 and Fig. 4; §6.2.4 and Table 2.','Automated constrained stock trading.','Portfolio value growth with costs and turbulence control.','Change in portfolio value net of transaction costs.','PPO, A2C, DDPG; rolling Sharpe-based ensemble selection.','Dow 30 daily WRDS data; training 2009–2015, testing Jan. 2016–8 May 2020.','Return, volatility, drawdown, Sharpe.','Table 2: ensemble Sharpe 1.30, DJIA .47, minimum variance .45.','Defines value-change objective; no identity with terminal MV.','No equilibrium mean–variance treatment.','DJIA and minimum-variance comparator, no true dynamic optimum.','Adapt value increments with zero costs and undiscounted finite horizon. Measures preference alignment; does not reproduce PPO/DDPG or the historical result.')
add('moody2001','John Moody; Matthew Saffell','Learning to Trade via Direct Reinforcement',2001,'IEEE Transactions on Neural Networks 12(4), 875–889','https://doi.org/10.1109/72.935097','IDSIA-hosted 17-page manuscript, visually read because text encoding is corrupted.','§II-D, Eqs. (12)–(17), PDF pp. 3–4; §III-A Eq. (31); §IV-A, Fig. 5; §IV-C.2, Fig. 8.','Trading and stock/T-bill allocation.','Risk-adjusted trading performance.','Differential Sharpe Eq. (14), EWMA updates Eq. (15); also differential downside-deviation reward.','Recurrent reinforcement learning; Q-learning/advantage updating comparisons.','Synthetic prices; USD/GBP; monthly S&P500/T-bills with 1970–1994 test period.','Profit and Sharpe; downside risk in FX example.','§IV-C.2 reports annualised Sharpe .83 for RRL, .63 for Q-trader, .34 buy-and-hold.','Yes: derives DSR as first-order Sharpe change.','No terminal MV equilibrium equivalence.','Simple market examples; no known optimal real-market policy.','Adapt unscaled DSR on an augmented (wealth,A,B) tree. Original online gradient update is not identical to maximising an undiscounted sum of DSR signals.')
add('bisi2020','Lorenzo Bisi; Luca Sabbioni; Edoardo Vittori; Matteo Papini; Marcello Restelli','Risk-Averse Trust Region Optimization for Reward-Volatility Reduction',2020,'Proceedings of IJCAI-20, 4583–4589','https://doi.org/10.24963/ijcai.2020/632','Published proceedings PDF, saved and read.','§3 Eqs. (3)–(6); §§4–5, Algorithm 1; §7.1–7.2, Fig. 1(a)–(d).','Trading with short-term risk control.','Expected reward minus occupancy-weighted per-step reward variance.','Trading P&L minus turnover costs; policy-dependent centred quadratic transformation.','Trust Region Volatility Optimization (TRVO), extending TRPO.','Daily S&P500 through 2019; minute USD/EUR and USD/JPY, train 2017/test 2018.','Mean-volatility and mean-variance frontiers.','Fig. 1 reports broader/frontier improvements over exponential rewards; S&P results are in-sample.','Yes: reward-volatility Bellman/gradient theory and return-variance bound.','Distinguishes risk measures; does not target the terminal-MV subgame equilibrium here.','No closed-form optimum for historical tasks.','Direct prior art against broad reward-analysis novelty. We compare its per-step criterion with an independently specified terminal equilibrium; do not call its chosen short-term objective wrong.')
add('zhang2021','Shangtong Zhang; Bo Liu; Shimon Whiteson','Mean-Variance Policy Iteration for Risk-Averse Reinforcement Learning',2021,'Proceedings of AAAI 35(12), 10905–10913','https://doi.org/10.1609/aaai.v35i12.17302','arXiv:2004.10888v6, 7 April 2022; differs in date from published 2021 proceedings.','“Mean-Variance RL”, Eq. (2); “Mean-Variance Policy Iteration”, Eqs. (3)–(4), Algorithm 1, Propositions 1–2; “Experiments”, Table 1.','Scalable risk-averse RL.','Discounted-occupancy per-step mean–variance.','Transformed reward r − λr² + 2λry; y updated by policy evaluation.','MVPI, instantiated with TD3; offline density-ratio variant.','Eight noisy-action MuJoCo tasks and an offline benchmark; not financial prices.','Risk-aware score, mean, variance, Sharpe-like ratio.','Reports strong risk-aware results versus TD3 and risk-averse baselines; not universal dominance on every metric.','Yes, explicitly distinguishes per-step and total-return variance.','No financial subgame-equilibrium target.','Small illustrative MDP; no closed-form MuJoCo optimum.','Finite-horizon uniform-time adaptation added. At zero interest its iid fixed point equals our scalar calibration: that formula alone is not a defensible novelty claim.')
add('wang2020','Haoran Wang; Xun Yu Zhou','Continuous-Time Mean-Variance Portfolio Selection: A Reinforcement Learning Framework',2020,'Mathematical Finance 30(4), 1273–1308','https://doi.org/10.1111/mafi.12281','arXiv:1904.11392, saved 39-page preprint; section references refer to this version.','§2 Eq. (11); §3 Theorems 1 and 3; §4; §5.1 Table 1, §§5.2–5.3.','Learn continuous-time mean–variance allocation.','Precommitted terminal MV via a mean constraint and quadratic embedding.','Terminal squared deviation plus entropy regularisation.','Exploratory mean–variance (EMV), policy evaluation/improvement.','Simulated GBM parameter grid and nonstationary simulations.','Terminal return, variance, Sharpe; algorithm comparisons.','§5.1 reports EMV best Sharpe in 23 of 28 tested cases.','Yes: objective and optimal exploratory control derived.','Uses precommitment; not an equilibrium solver.','Closed-form Gaussian exploratory policy and classical limit.','Essential positive control: objective-faithful RL already exists. Our discrete reward-family audit asks a different question; no EMV replication claimed.')
add('dai2023','Min Dai; Yuchao Dong; Yanwei Jia','Learning Equilibrium Mean-Variance Strategy',2023,'Mathematical Finance 33(4), 1166–1212','https://doi.org/10.1111/mafi.12402','NUS RMI Working Paper 2021-02, March 2021, 52 pages, read via web PDF. Local download blocked; journal section numbering not asserted.','Working version §§2–3, §4.2 Theorem 2; §5 Algorithm 1; §6.1–6.2, Fig. 1.','Learn equilibrium allocation under stochastic investment opportunities.','Mean–variance of log returns plus entropy.','Objective-specific equilibrium TD/policy updates, not arbitrary additive wealth increments.','Exploratory equilibrium policy iteration and parameterised learning.','Simulated Gaussian mean-return model; perfect/noisy factor observations.','Policy deviation from theoretical solution and convergence.','Fig. 1 shows learned policies close to the analytic target, with increased error under observation noise.','Yes.','Yes, explicitly central.','Semi-analytic equilibrium; closed form in Gaussian factor model.','Refutes any first-equilibrium-RL claim. Our target is discrete terminal wealth MV and an audit of common rewards, not their log-MV learning problem.')
add('ling2000','Duan Li; Wan-Lung Ng','Optimal Dynamic Portfolio Selection: Multiperiod Mean-Variance Formulation',2000,'Mathematical Finance 10(3), 387–406','https://doi.org/10.1111/1467-9965.00100','Journal PDF mirrored at tianjiablog.wordpress.com; saved.','§§3–4, Theorems 1–2 (embedding); §5 riskless-asset case.','Multiperiod portfolio selection.','Terminal mean–variance at the initial date.','No RL reward; auxiliary quadratic terminal objective.','Embedding and stochastic linear-quadratic control.','Independent, potentially time-varying return moments.','Efficient frontier and terminal mean/variance.','Analytic optimal policies/frontiers via embedding.','Analyses the objective transformation, not additive RL rewards.','Supplies precommitted optimum, not subgame equilibrium.','Yes, core exact reference.','Our precommitment reference is established theory. Reward-design comparisons must specify whether this or equilibrium is the intended target.')
add('basak2010','Suleyman Basak; Georgy Chabakauri','Dynamic Mean-Variance Asset Allocation',2010,'The Review of Financial Studies 23(8), 2970–3016','https://doi.org/10.1093/rfs/hhq028','Author thesis chapter 2, “Dynamic Mean-Variance Asset Allocation”, read; journal full text unavailable. Chapter numbering is not journal numbering.','Thesis chapter 2 §2.2.2, Proposition 2.1, Eqs. (148)–(149); §2.2.2 Remark 1; §2.2.4; discrete-time extension in §2.4.','Dynamic allocation under stochastic opportunities.','Time-consistent terminal wealth mean–variance.','No RL reward; equilibrium control and associated utility interpretation.','Recursive equilibrium analysis and analytic specialisations.','Continuous-time incomplete-market models; discrete-time extensions.','Policy, hedging demand, terminal moments.','Decomposes risky demand into myopic and intertemporal hedging components.','Discusses objectives giving the same policy (Remark 1).','Yes.','Analytic equilibria in tractable market models.','Foundational benchmark and hedge precedent. Our finite-regime correction is a discrete audit construction, not the discovery of intertemporal hedging or inverse objectives.')
add('ng1999','Andrew Y. Ng; Daishi Harada; Stuart Russell','Policy Invariance under Reward Transformations: Theory and Application to Reward Shaping',1999,'Proceedings of ICML, 278–287','https://ai.stanford.edu/~ang/papers/shaping-icml99.pdf','Author-hosted 10-page conference paper; visually read due to encoding. No DOI asserted.','§3 Theorem 1, Eq. (2), Corollary 2; §4 Figures 1–2; Appendix A.','Reward shaping without changing optimal policies.','Expected discounted reward.','Potential difference γΦ(s′)−Φ(s).','Policy-invariance theorem; SARSA gridworld examples.','Synthetic gridworlds, not markets.','Policy invariance and learning steps.','Potential shaping preserves optimal policies under stated conditions and can accelerate learning.','Yes.','Not a mean–variance equilibrium treatment.','Known small MDPs.','Our redesign deliberately changes the raw reward optimum. Policy-invariant shaping cannot by itself correct a mismatched target.')
add('bjork2014','Tomas Björk; Agatha Murgoci','A Theory of Markovian Time-Inconsistent Stochastic Control in Discrete Time',2014,'Finance and Stochastics 18(3), 545–592','https://doi.org/10.1007/s00780-014-0234-y','Publisher metadata and abstract only; full-text verification OPEN. Not counted as a paper fully read.','Publisher abstract only; no theorem number or detailed comparison asserted.','Markovian time-inconsistent control.','General time-inconsistent criteria.','Not extracted from full text.','Game-theoretic extended dynamic programming (abstract).','General control setting (abstract).','Equilibrium policies and values (abstract).','Abstract states an associated time-consistent problem can reproduce equilibrium control and value.','Abstract supports existence of an equivalent control problem.','Yes.','Not independently extracted.','Requires conservative novelty: existence of an equivalent reward problem is prior art. Exact theorem-level comparison remains open.')
(ROOT/'literature'/'ledger.json').write_text(json.dumps(rows,indent=2,ensure_ascii=False))
head='''# Primary-paper comparison ledger

Audit date: 21–22 September 2026. Locators refer to the **version actually read**. A manuscript is not silently treated as the published version. Saved PDFs and SHA-256 values are in download_manifest.json. Numerical claims below are reports by the cited authors, not replications by this project.

| ID | Verified citation | Access / version | Role |
|---|---|---|---|
'''
for r in rows:head+=f"| {r['key']} | {r['authors']} ({r['year']}). [{r['title']}]({r['url']}). {r['venue']}. | {r['version']} | {r['project_relation']} |\n"
for r in rows:
 head+='\n## '+r['key']+'\n\n| Requested field | Extraction |\n|---|---|\n'
 for k in ['locator','problem','objective','reward','algorithm','market','metric','result','studies_reward_objective','time_inconsistency','known_benchmark','project_relation']:head+=f"| {k.replace('_',' ')} | {r[k]} |\n"
head+='''
## Search scope and unresolved access

Primary papers were located through author/institution repositories, arXiv, conference proceedings and publisher records. Search phrases included financial RL portfolio reward mean–variance, differential Sharpe, equilibrium mean–variance RL, reward-volatility, mean–variance policy iteration, and reward calibration/mismatch. This is a targeted relevance search, not an exhaustive systematic review or a proof of novelty. Search results and cited references led to the Bisi/Zhang additions, which materially weaken a novelty claim based only on scalar calibration.

Ritter (2017), “Machine Learning for Trading”, SSRN 3015609, DOI 10.2139/ssrn.3015609: author PDF returned 403. No unverified formulation or result is attributed to it; Kolm–Ritter's inspected manuscript is used directly instead. Björk–Murgoci full text and journal-version concordance for thesis/working-paper sources remain open.

The archived DeMiguel reference used the wrong year (2015 instead of 2014 for RFS volume 27). It is omitted from the revised argument because its primary paper was not needed/read. Broad survey-based assertions and unsupported “first” claims are removed. Basak–Chabakauri's prior associated-objective remark and Dai–Dong–Jia's equilibrium learner must be considered before any publication-priority claim.

## Adaptation rules

Published reward formulas are tested in a common controlled market, not their original data or algorithm. No result here replicates published backtest performance. Quadratic coefficient .05 comes from Kolm–Ritter's κ=.1 and Eq. (10); changing wealth units changes its meaning. It is a sensitivity diagnostic, not evidence of an inferior published hyperparameter. Main calibrated comparisons share the same φ and units. Zhang MVPI is adapted from discounted infinite-horizon occupancy to uniformly weighted finite-horizon increments; its fixed-point convergence is checked, but global optimality for the new nonlinear criterion is not claimed. DSR uses the full augmented finite-tree state; the paper's online local-gradient algorithm is not reproduced.
'''
(ROOT/'literature'/'LITERATURE_LEDGER.md').write_text(head)
# Exact bibliography records; identifiers belong to publications, locators to read versions.
bib=[]
for r in rows:
 entry=['@misc{'+r['key']+',',f"  author = {{{r['authors'].replace('; ', ' and ')}}},",f"  title = {{{r['title']}}},",f"  year = {{{r['year']}}},",f"  howpublished = {{{r['venue']}}},",f"  url = {{{r['url']}}},",f"  note = {{{r['version']}}}",'}'];bib.append('\n'.join(entry))
(ROOT/'literature'/'references.bib').write_text('\n\n'.join(bib))
print('Twelve comparison records; eleven primary versions inspected, one abstract-only.')
